import { chromium } from '@playwright/test';
const out = process.argv[2];
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium', args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage({ viewport: { width: 1600, height: 950 } });
const logs = [];
page.on('console', (m) => { if (m.type() === 'error') logs.push(`${m.type()}: ${m.text()}`); });
page.on('pageerror', (e) => logs.push(`pageerror: ${e.message}`));
const shot = async (n) => { await page.screenshot({ path: `${out}/${n}.png` }); console.log('shot', n); };
await page.goto('http://127.0.0.1:5173/');
await page.fill('#u', 'analyst'); await page.fill('#p', 'strata-demo');
await page.click('button:has-text("Sign in")');
await page.waitForTimeout(10000);
await shot('t1-ops');
await page.click('.tree-item:has-text("Hangar 1")');
await page.waitForTimeout(2500);
await page.click('.ev-row:has-text("north wall")');
await page.waitForTimeout(3500);
await shot('t2-evidence');
await page.click('button:has-text("Close")');
await page.click('[role=tab]:has-text("COVERAGE")');
await page.waitForTimeout(7000);
await shot('t3-coverage');
await page.click('[role=tab]:has-text("DIFF")');
await page.waitForTimeout(6000);
await shot('t4-diff');
await page.click('[role=tab]:has-text("NOW")');
await page.click('button:has-text("Ask the record")');
await page.fill('input[aria-label="Copilot question"]', 'What changed around Building G during the last hour?');
await page.keyboard.press('Enter');
await page.waitForTimeout(4000);
await shot('t5-copilot');
await page.goto('http://127.0.0.1:5173/incidents');
await page.waitForTimeout(2500);
await page.click('.list-row >> nth=0');
await page.waitForTimeout(2500);
await shot('t6-incident');
await page.click('button:has-text("Enter reconstruction environment")');
await page.waitForTimeout(9000);
await shot('t7-incident-world');
for (const p of ['sensors/C12', 'system', 'simulation', 'audit', 'admin', 'reconstructions']) {
  await page.goto(`http://127.0.0.1:5173/${p}`);
  await page.waitForTimeout(3500);
  await shot(`p-${p.replace('/', '-')}`);
}
await page.goto('http://127.0.0.1:5173/evidence');
await page.waitForTimeout(1500);
await page.click('button:has-text("IDENTITY HAND-OFF")');
await page.waitForTimeout(1000);
await page.click('button:has-text("Search recorded observations")');
await page.waitForTimeout(6000);
await shot('p-handoff');
console.log(logs.slice(0, 40).join('\n'));
await browser.close();
